"""
ProcureOS v2 — Purchase Order Routes
POST /po/<proc_id>/generate
GET  /po/<po_id>/download
GET  /po  (list all POs)
"""
import base64
import io
from datetime import datetime, timezone
from flask import Blueprint, request, jsonify, send_file
from flask_jwt_extended import jwt_required, get_jwt_identity
from models import db, User, Procurement, ProcurementVendor, PurchaseOrder, Vendor, Company, Activity
from agents.email_agent import EmailAgent

po_bp       = Blueprint('po', __name__)
email_agent = EmailAgent()


def current_user():
    return User.query.get(get_jwt_identity())


def log_activity(company_id, user_id, actor, action, detail='', procurement_id=None):
    db.session.add(Activity(
        company_id=company_id,
        procurement_id=procurement_id,
        user_id=user_id,
        actor=actor,
        action=action,
        detail=detail
    ))


def generate_po_number(company_id):
    count = PurchaseOrder.query.filter_by(company_id=company_id).count()
    date  = datetime.now(timezone.utc).strftime('%Y%m%d')
    return f'PO-{date}-{str(count + 1).zfill(4)}'


def build_po_html(po_number, company, vendor, proc, pv):
    unit_price  = float(pv.quote_price)
    total       = unit_price * proc.quantity
    return f"""
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="UTF-8">
    <style>
      body {{ font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #111; }}
      .header {{ background: #1e40af; color: white; padding: 28px; border-radius: 8px 8px 0 0; text-align: center; }}
      .header h1 {{ margin: 0; font-size: 26px; }}
      .header .po-num {{ font-size: 18px; margin-top: 8px; opacity: 0.9; }}
      .section {{ border: 1px solid #e5e7eb; padding: 20px; border-top: none; }}
      .section:last-of-type {{ border-radius: 0 0 8px 8px; }}
      .grid2 {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }}
      table {{ width: 100%; border-collapse: collapse; margin-top: 16px; }}
      th {{ background: #f3f4f6; padding: 10px; text-align: left; border-bottom: 2px solid #e5e7eb; }}
      td {{ padding: 10px; border-bottom: 1px solid #e5e7eb; }}
      .total {{ font-size: 18px; font-weight: bold; text-align: right; }}
      .footer {{ text-align: center; color: #9ca3af; font-size: 12px; margin-top: 24px; }}
      .label {{ font-size: 11px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; }}
      .value {{ font-size: 15px; font-weight: 500; margin-top: 2px; }}
    </style>
    </head>
    <body>
    <div class="header">
      <h1>PURCHASE ORDER</h1>
      <div class="po-num">{po_number}</div>
      <div style="margin-top:6px;font-size:13px;opacity:0.8">{datetime.now(timezone.utc).strftime('%B %d, %Y')}</div>
    </div>

    <div class="section">
      <div class="grid2">
        <div>
          <div class="label">From (Buyer)</div>
          <div class="value">{company.name}</div>
        </div>
        <div>
          <div class="label">To (Vendor)</div>
          <div class="value">{vendor.company_name}</div>
          <div style="color:#6b7280;font-size:13px">{vendor.contact_email or ''}</div>
        </div>
      </div>
    </div>

    <div class="section">
      <table>
        <thead>
          <tr>
            <th>Item Description</th>
            <th style="text-align:center">Qty</th>
            <th style="text-align:right">Unit Price</th>
            <th style="text-align:right">Total</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{proc.item_name}</td>
            <td style="text-align:center">{proc.quantity} {proc.unit or 'units'}</td>
            <td style="text-align:right">${unit_price:,.2f}</td>
            <td style="text-align:right"><strong>${total:,.2f}</strong></td>
          </tr>
        </tbody>
      </table>
      <div class="total" style="margin-top:12px">Total: ${total:,.2f}</div>
    </div>

    <div class="section">
      <div class="grid2">
        <div>
          <div class="label">Delivery</div>
          <div class="value">{pv.quote_delivery_days or '—'} business days</div>
        </div>
        <div>
          <div class="label">Payment Terms</div>
          <div class="value">{pv.quote_payment_terms or company.default_payment_terms or 'Net 30'}</div>
        </div>
      </div>
      {f'<div style="margin-top:16px"><div class="label">Notes</div><div class="value">{pv.quote_notes}</div></div>' if pv.quote_notes else ''}
    </div>

    <div class="footer">
      This is an official purchase order from {company.name}.<br>
      Generated by ProcureOS on {datetime.now(timezone.utc).strftime('%B %d, %Y at %H:%M UTC')}
    </div>
    </body>
    </html>
    """


# ── GENERATE & SEND PO ────────────────────────────────────────────────────────

@po_bp.route('/<proc_id>/generate', methods=['POST'])
@jwt_required()
def generate_po(proc_id):
    user = current_user()
    if user.role not in ('admin', 'approver'):
        return jsonify({'error': 'Admin or approver access required'}), 403

    proc = Procurement.query.filter_by(
        id=proc_id, company_id=user.company_id
    ).first()
    if not proc:
        return jsonify({'error': 'Not found'}), 404

    if proc.status not in ('approved', 'pending_approval'):
        return jsonify({'error': f'Cannot generate PO. Status: {proc.status}'}), 400

    if not proc.selected_vendor_id:
        return jsonify({'error': 'No winner selected'}), 400

    # Check existing PO
    existing = PurchaseOrder.query.filter_by(procurement_id=proc_id).first()
    if existing:
        return jsonify({'error': 'PO already generated', 'po': existing.to_dict()}), 409

    vendor  = Vendor.query.get(proc.selected_vendor_id)
    company = Company.query.get(user.company_id)
    pv      = ProcurementVendor.query.filter_by(
        procurement_id=proc_id,
        vendor_id=proc.selected_vendor_id
    ).first()

    if not pv or not pv.quote_price:
        return jsonify({'error': 'Quote not found for selected vendor'}), 400

    # Validate total (catch decimal errors — flag if >10x average)
    unit_price  = float(pv.quote_price)
    total_value = unit_price * proc.quantity
    warning     = None
    if proc.total_value:
        avg = float(proc.total_value)
        if total_value > avg * 10:
            warning = f'Warning: Total ${total_value:,.2f} seems unusually high. Please verify.'

    po_number = generate_po_number(user.company_id)
    html      = build_po_html(po_number, company, vendor, proc, pv)

    # Send email to vendor
    email_sent = False
    if vendor and vendor.contact_email:email_sent = email_agent.send_po(
    to=vendor.contact_email,
    vendor_name=vendor.company_name,
    po_number=po_number,
    company_name=company.name,
    item_name=proc.item_name,
    quantity=proc.quantity,
    unit_price=unit_price,
    total=total_value,
    delivery_days=pv.quote_delivery_days or 0,
    payment_terms=pv.quote_payment_terms or company.default_payment_terms or 'Net 30',
)

    po = PurchaseOrder(
        company_id=user.company_id,
        procurement_id=proc_id,
        vendor_id=vendor.id,
        po_number=po_number,
        total_amount=total_value,
        pdf_data=base64.b64encode(html.encode()).decode(),
        sent_at=datetime.now(timezone.utc) if email_sent else None,
    )
    db.session.add(po)

    proc.status = 'completed'

    log_activity(
        company_id=user.company_id,
        user_id=user.id,
        actor=user.full_name,
        action='Purchase Order generated',
        detail=f'{po_number} — ${total_value:,.2f}',
        procurement_id=proc_id
    )

    db.session.commit()

    return jsonify({
        'po': po.to_dict(),
        'email_sent': email_sent,
        'warning': warning,
        'message': f'PO {po_number} generated successfully.'
    })


# ── DOWNLOAD PO ───────────────────────────────────────────────────────────────

@po_bp.route('/<po_id>/download', methods=['GET'])
@jwt_required()
def download_po(po_id):
    user = current_user()
    po   = PurchaseOrder.query.filter_by(
        id=po_id, company_id=user.company_id
    ).first()
    if not po:
        return jsonify({'error': 'Not found'}), 404

    html_content = base64.b64decode(po.pdf_data).decode()
    return send_file(
        io.BytesIO(html_content.encode()),
        mimetype='text/html',
        as_attachment=True,
        download_name=f'{po.po_number}.html'
    )


# ── LIST POs ──────────────────────────────────────────────────────────────────

@po_bp.route('', methods=['GET'])
@jwt_required()
def list_pos():
    user = current_user()
    pos  = PurchaseOrder.query.filter_by(
        company_id=user.company_id
    ).order_by(PurchaseOrder.created_at.desc()).all()
    return jsonify({'purchase_orders': [p.to_dict() for p in pos]})